### PR TITLE
Issue336

### PR DESCRIPTION
**Pull request by ktschap**
closes https://github.com/project-callisto/callisto-core/issues/336

---

Hello - for issue https://github.com/project-callisto/callisto-core/issues/336, I took a pass at an implementation - if we have only a salt, generate a backwards compatible encode_prefix, and only pass in the encode prefix to make_key in hashers.py. The implementation assumes that:
* salt DB field in delivery_report is filled in with a salt with an empty encode_prefix for older reports
* salt was used with PBKDF2/SHA256, with settings.ORIGINAL_KEY_ITERATIONS
Note that I was not able to have the current codebase generate a record in sqlite matching the above (salt w/o prefix field), so my testing involved manually modifying the DB fields for a couple of delivery_report records.
Please advise on whether my assumptions are off, happy to change this approach as needed.

### CODE REVIEW

**Comment by lynncyrin** [comment]
Ah, thanks so much!!!

> salt DB field in delivery_report is filled in with a salt with an empty encode_prefix for older reports

this is true

> salt was used with PBKDF2/SHA256, with settings.ORIGINAL_KEY_ITERATIONS

as far as I can remember, more or less yes. I think the specifics of the old implementation are something for me to worry about, though!

**Comment by lynncyrin** [comment]
The one thing that's making me hesitate on merging this PR is that we have this code here for turning a salt into an encode prefix

https://github.com/ktschap/callisto-core/blob/e482d4a947cd602b6a1af55c35806731fd283668/callisto_core/delivery/model_helpers.py#L13-L15

and I think there should be more tests around the `<algorithm>$<iterations>$<salt>$` format, which prior to this PR was only present as a comment in models.py

**Comment by lynncyrin** [comment]
✔️ https://github.com/project-callisto/callisto-core/pull/360/commits/4f929c15b23cb1dadf8ba912d26dea473a7c79b3 addresses the previous comment

**Comment by ktschap** [comment]
Hi - take a look at my latest commit, I tweaked it so that the django libs will generate the prefix for us, and then tested it works with make_key

**Comment by lynncyrin** [comment]
This is most likely ready to merge! Just need to find time to review it

**Comment by lynncyrin** [comment]
Also super sorry it took so long for me to provide that review feedback @ktschap! I'm usually a ton more proactive about this sort of thing 😅

**Pull request closed without merging**
